export const HANDLE_PRODUCTDETAIL = 'HANDLE_PRODUCTDETAILS'
export const HANDLE_CARTS = 'HANDLE_CARTS'
export const HANDLE_CARTS_QUANTITY = 'HANDLE_CARTS_QUANTITY'
export const HANDLE_CARTS_DELETE = 'HANDLE_CARTS_DELETE'